<?php

use Drupal\user\Entity\User;
use Drupal\Node\NodeInterface;

/**
 * @file
 * Primary module hooks for node workflow module.
 */

 /**
  * Implements hook_node_insert()
  */
  // function sales_workflow_node_insert(){
  //   $to = \Drupal::currentUser()->getEmail();
  // \Drupal::service('email_factory')->sendTypedEmail('sales_email_update', 'new', $to);
  // }

 /**
  * Implements hook_node_presave
  */

  function sales_workflow_node_presave(NodeInterface $node){
    $ids = \Drupal::entityQuery('user')
      ->accessCheck(TRUE)
      ->condition('status', 1)
      ->condition('roles', 'sales_head')
      ->execute();
   $users = User::loadMultiple($ids);

    if($node->isNew()){
      foreach($users as $user){
        \Drupal::service('email_factory')->sendTypedEmail('sales_email_update', 'new', $user, $node);
      }
    }else{
      foreach($users as $user){
        \Drupal::service('email_factory')->sendTypedEmail('sales_email_update', 'update', $user, $node);
      }
    }

  \Drupal::messenger()->addMessage("Sent emails to Sales Head");

  }
